name: Hello World Workflow

on:
  push:
    branches:
      - workflow-test

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
